import type {ControlState, FlowSolver, Scenario, SolverId, StepReport} from "../core/contracts.js";
import {NacaFoil} from "../core/geometry.js";
import {bounds2d, dimensions} from "../core/grid.js";
import {controlAt} from "../core/scenario.js";
import {createSolver} from "../solvers/factory.js";
import type {ViewerSnapshot} from "./protocol.js";
import {TracerSystem} from "./tracers.js";

export class ViewerModel {
  public solver: FlowSolver; public readonly tracers: TracerSystem; public time = 0; public paused = false; public vorticityVisible = true; public cropEnabled: boolean; public status = "warming"; public appliedCommand = 0; public revision = 0;
  private manualAngle: number | null = null; private angularVelocity = 0; private poseSamples: {time: number; angle: number}[] = []; private lastWall = performance.now(); private stepRate: number | null = null; private simulatedPerWall: number | null = null; private lastReport: StepReport = {requestedDt: 0, advancedDt: 0, substeps: 0, maxSpeed: 0, warnings: []};
  public constructor(public readonly scenario: Scenario, solverId: SolverId) { this.solver = createSolver(solverId); this.solver.initialize(scenario, scenario.seed); this.tracers = new TracerSystem(scenario); this.cropEnabled = scenario.solverOptions.viewerCropDefault ?? false; }
  public control(nextTime: number): ControlState { const scheduled = controlAt(this.scenario, nextTime); return this.manualAngle === null ? scheduled : {time: nextTime, angleDegrees: this.manualAngle, angularVelocityDegrees: this.angularVelocity}; }
  public setAngle(angle: number, timestamp: number): void { const selected = Math.max(-30, Math.min(30, angle)); this.poseSamples.push({time: timestamp, angle: selected}); const cutoff = timestamp - 80; while (this.poseSamples.length > 2 && (this.poseSamples[1]?.time ?? timestamp) < cutoff) this.poseSamples.shift(); const first = this.poseSamples[0]; if (first !== undefined && timestamp > first.time) { const reference = Math.max(Math.hypot(this.scenario.freestream[0] ?? 0, this.scenario.freestream[1] ?? 0), 1e-6); const maximum = 8 * reference / this.scenario.foil.chord * 180 / Math.PI; this.angularVelocity = Math.max(-maximum, Math.min(maximum, (selected - first.angle) / ((timestamp - first.time) / 1000))); } this.manualAngle = selected; this.status = "manual control"; }
  public releaseAngle(): void { this.angularVelocity = 0; this.poseSamples = []; }
  public setReynolds(reynolds: number): void { this.solver.setReynolds(reynolds); this.status = "Re changed; warming"; this.stepRate = null; this.simulatedPerWall = null; }
  public reset(): void { const id = this.solver.info.id; this.solver = createSolver(id); this.solver.initialize(this.scenario, this.scenario.seed); this.time = 0; this.manualAngle = null; this.angularVelocity = 0; this.tracers.reseed(); this.status = "warming"; this.stepRate = null; this.simulatedPerWall = null; }
  public switchSolver(id: SolverId): boolean { if (id === this.solver.info.id) return true; const incoming = createSolver(id); incoming.initialize(this.scenario, this.scenario.seed); incoming.setReynolds(this.solver.reynolds); const control = this.control(this.time); const outcome = incoming.importState(this.solver.exportState(), control); if (outcome.status === "rejected") { this.status = `switch rejected: ${outcome.reason}`; return false; } this.solver = incoming; this.status = `switched; discarded ${outcome.discardedState.join(", ")}`; this.stepRate = null; this.simulatedPerWall = null; return true; }
  public step(): void { if (this.paused) return; const dt = this.scenario.outputDt; const started = performance.now(); try { this.lastReport = this.solver.advance(this.control(this.time + dt), dt); this.time += this.lastReport.advancedDt; const displayScale = Math.min(1.5, Math.max(0.5, 1 + 0.5 * Math.log10(this.solver.reynolds / Math.max(this.scenario.reynolds, 1)))); this.tracers.advance(this.solver, dt, displayScale); const elapsed = Math.max((performance.now() - started) / 1000, 1e-9); const instantRate = 1 / elapsed; const instantThroughput = dt / elapsed; this.stepRate = this.stepRate === null ? instantRate : 0.85 * this.stepRate + 0.15 * instantRate; this.simulatedPerWall = this.simulatedPerWall === null ? instantThroughput : 0.85 * this.simulatedPerWall + 0.15 * instantThroughput; this.status = "running"; this.lastWall = started; }
    catch (error) { const id = this.solver.info.id; try { const replacement = createSolver(id); replacement.initialize(this.scenario, this.scenario.seed); replacement.setReynolds(this.solver.reynolds); this.solver = replacement; this.tracers.reseed(); this.status = `fresh recovery after ${error instanceof Error ? error.name : "failure"}`; this.stepRate = null; this.simulatedPerWall = null; } catch { this.paused = true; this.status = "recovery failed; paused"; } } }
  private vorticity(): Float32Array { const {nx, ny, dx, dy} = dimensions(this.scenario.domain); const velocity = this.solver.exportState().velocity; const output = new Float32Array(nx * ny); if (!this.vorticityVisible) return output; for (let y = 1; y + 1 < ny; y += 1) for (let x = 1; x + 1 < nx; x += 1) { const dvdx = ((velocity[2 * (y * nx + x + 1) + 1] ?? 0) - (velocity[2 * (y * nx + x - 1) + 1] ?? 0)) / (2 * dx); const dudy = ((velocity[2 * ((y + 1) * nx + x)] ?? 0) - (velocity[2 * ((y - 1) * nx + x)] ?? 0)) / (2 * dy); output[y * nx + x] = dvdx - dudy; } return output; }
  public snapshot(): ViewerSnapshot { const {nx, ny} = dimensions(this.scenario.domain); const bounds = bounds2d(this.scenario.domain); const angle = this.control(this.time).angleDegrees; const diagnostics = this.solver.diagnostics().values; this.revision += 1; return {kind: "snapshot", revision: this.revision, appliedCommand: this.appliedCommand, solverId: this.solver.info.id, time: this.time, angleDegrees: angle, reynolds: this.solver.reynolds, paused: this.paused, vorticityVisible: this.vorticityVisible, cropEnabled: this.cropEnabled, tracerMode: this.tracers.mode, stepRate: this.stepRate, simulatedPerWall: this.simulatedPerWall, substeps: this.lastReport.substeps, maxSpeed: this.lastReport.maxSpeed, diagnostics, status: this.status, resolution: [nx, ny], bounds: [bounds.x, bounds.y], tracerPositions: this.tracers.positions.slice(), pathSegments: this.tracers.segments(), vorticity: this.vorticity(), foilOutline: new NacaFoil(this.scenario.foil).outline(angle)}; }
}
