import type {FlowSolver, Scenario} from "../core/contracts.js";
import {bounds2d} from "../core/grid.js";
import {Pcg32} from "../core/rng.js";

export class TracerSystem {
  public readonly positions: Float32Array; private readonly history: Float32Array; private cursor = 0; private readonly rng: Pcg32; public mode: "display" | "flow" = "display";
  public constructor(private readonly scenario: Scenario, public readonly count = 8192, private readonly depth = 12) { this.positions = new Float32Array(2 * count); this.history = new Float32Array(2 * count * depth); this.rng = new Pcg32(scenario.seed, 97); this.reseed(); }
  public reseed(): void { const {x, y} = bounds2d(this.scenario.domain); for (let index = 0; index < this.count; index += 1) { this.positions[2 * index] = x[0] + this.rng.nextFloat32() * (x[1] - x[0]); this.positions[2 * index + 1] = y[0] + this.rng.nextFloat32() * (y[1] - y[0]); } for (let frame = 0; frame < this.depth; frame += 1) this.history.set(this.positions, frame * this.positions.length); this.cursor = 0; }
  public advance(solver: FlowSolver, dt: number, displayScale: number): void { const sampled = solver.sampleVelocity(this.positions); const {x, y} = bounds2d(this.scenario.domain); for (let index = 0; index < this.count; index += 1) { const offset = 2 * index; const scale = this.mode === "display" ? displayScale : 1; this.positions[offset] = (this.positions[offset] ?? 0) + dt * scale * (sampled[offset] ?? 0); this.positions[offset + 1] = (this.positions[offset + 1] ?? 0) + dt * scale * (sampled[offset + 1] ?? 0); if ((this.positions[offset] ?? 0) > x[1] || (this.positions[offset] ?? 0) < x[0] || (this.positions[offset + 1] ?? 0) > y[1] || (this.positions[offset + 1] ?? 0) < y[0]) { this.positions[offset] = x[0] + 0.01 * (x[1] - x[0]) * this.rng.nextFloat32(); this.positions[offset + 1] = y[0] + this.rng.nextFloat32() * (y[1] - y[0]); for (let frame = 0; frame < this.depth; frame += 1) { this.history[frame * this.positions.length + offset] = this.positions[offset] ?? 0; this.history[frame * this.positions.length + offset + 1] = this.positions[offset + 1] ?? 0; } } } this.cursor = (this.cursor + 1) % this.depth; this.history.set(this.positions, this.cursor * this.positions.length); }
  public segments(): Float32Array { const output = new Float32Array(4 * this.count * (this.depth - 1)); let cursor = 0; for (let age = this.depth - 1; age > 0; age -= 1) { const older = (this.cursor - age + this.depth) % this.depth; const newer = (older + 1) % this.depth; for (let index = 0; index < this.count; index += 1) { const offset = 2 * index; output[cursor] = this.history[older * this.positions.length + offset] ?? 0; output[cursor + 1] = this.history[older * this.positions.length + offset + 1] ?? 0; output[cursor + 2] = this.history[newer * this.positions.length + offset] ?? 0; output[cursor + 3] = this.history[newer * this.positions.length + offset + 1] ?? 0; cursor += 4; } } return output; }
}
