import type {CanonicalFlowState, ControlState, Diagnostics, FlowSolver, FloatArray, ImportOutcome, Scenario, SolverInfo, StepReport} from "../core/contracts.js";
import {NumericalFailure} from "../core/contracts.js";
import {NacaFoil} from "../core/geometry.js";
import {allocate, bounds2d, dimensions, sampleCell} from "../core/grid.js";
import {fieldDiagnostics} from "../core/metrics.js";

const CX = [0, 1, 0, -1, 0, 1, -1, -1, 1] as const;
const CY = [0, 0, 1, 0, -1, 1, 1, -1, -1] as const;
const W = [4 / 9, 1 / 9, 1 / 9, 1 / 9, 1 / 9, 1 / 36, 1 / 36, 1 / 36, 1 / 36] as const;
const OPPOSITE = [0, 3, 4, 1, 2, 7, 8, 5, 6] as const;

export class LbmSolver implements FlowSolver {
  public readonly info: SolverInfo = {id: "lbm-d2q9", displayName: "D2Q9 TRT LBM", dimensions: [2], supportsMovingBoundary: true, acceleration: "typed-arrays"};
  public reynolds = 1;
  private effectiveReynolds = 1; private scenario: Scenario | null = null; private foil: NacaFoil | null = null;
  private populations: FloatArray = new Float32Array(); private scratch: FloatArray = new Float32Array(); private solid = new Uint8Array(); private time = 0; private control: ControlState = {time: 0, angleDegrees: 0, angularVelocityDegrees: 0};
  private latticeSpeed = 0.05; private omegaPlus = 1; private omegaMinus = 1; private referenceSpeed = 1;

  private requireScenario(): Scenario { if (this.scenario === null) throw new Error("solver is not initialized"); return this.scenario; }
  private equilibrium(direction: number, density: number, ux: number, uy: number): number { const cu = (CX[direction] ?? 0) * ux + (CY[direction] ?? 0) * uy; return (W[direction] ?? 0) * density * (1 + 3 * cu + 4.5 * cu * cu - 1.5 * (ux * ux + uy * uy)); }

  public initialize(scenario: Scenario, seed: number): void {
    void seed; if (scenario.domain.dimension !== 2) throw new RangeError("lbm-d2q9 supports only 2D"); this.scenario = scenario; this.foil = new NacaFoil(scenario.foil); this.reynolds = scenario.reynolds; this.time = 0; this.control = {time: 0, angleDegrees: scenario.controls[0]?.angleDegrees ?? 0, angularVelocityDegrees: 0};
    const {nx, ny, dx} = dimensions(scenario.domain); const count = nx * ny; this.populations = allocate(scenario.precision, 9 * count); this.scratch = allocate(scenario.precision, 9 * count); this.solid = new Uint8Array(count);
    this.referenceSpeed = Math.max(Math.hypot(scenario.freestream[0] ?? 0, scenario.freestream[1] ?? 0), scenario.solverOptions.initialCondition === "freestream" ? 1e-6 : 1);
    this.latticeSpeed = 0.05; this.configureRelaxation(); this.updateSolid(this.control);
    const velocity = this.initialVelocity();
    for (let cell = 0; cell < count; cell += 1) for (let q = 0; q < 9; q += 1) this.populations[q * count + cell] = this.equilibrium(q, 1, (velocity[2 * cell] ?? 0) * this.latticeSpeed / this.referenceSpeed, (velocity[2 * cell + 1] ?? 0) * this.latticeSpeed / this.referenceSpeed);
    void dx;
  }

  private configureRelaxation(): void { const scenario = this.requireScenario(); const {dx} = dimensions(scenario.domain); const chordCells = scenario.foil.chord / dx; const requestedNu = this.latticeSpeed * chordCells / this.reynolds; const minimumNu = 0.002; const nu = Math.max(requestedNu, minimumNu); const tauPlus = 0.5 + 3 * nu; const tauMinus = 0.5 + (3 / 16) / Math.max(tauPlus - 0.5, 1e-6); this.omegaPlus = 1 / tauPlus; this.omegaMinus = 1 / tauMinus; this.effectiveReynolds = this.latticeSpeed * chordCells / nu; }
  public setReynolds(reynolds: number): void { if (!(reynolds > 0) || !Number.isFinite(reynolds)) throw new RangeError("Reynolds must be finite and positive"); this.reynolds = reynolds; if (this.scenario !== null) this.configureRelaxation(); }

  private initialVelocity(): FloatArray { const scenario = this.requireScenario(); const {nx, ny, dx, dy} = dimensions(scenario.domain); const {x: bx, y: by} = bounds2d(scenario.domain); const output = allocate(scenario.precision, nx * ny * 2); for (let y = 0; y < ny; y += 1) for (let x = 0; x < nx; x += 1) { const cell = y * nx + x; const px = bx[0] + (x + 0.5) * dx; const py = by[0] + (y + 0.5) * dy; if (scenario.solverOptions.initialCondition === "taylor-green") { output[2 * cell] = Math.sin(px) * Math.cos(py); output[2 * cell + 1] = -Math.cos(px) * Math.sin(py); } else if (scenario.solverOptions.initialCondition === "poiseuille") { const center = (by[0] + by[1]) / 2; const radius = (by[1] - by[0]) / 2; output[2 * cell] = 1.5 * (1 - ((py - center) / radius) ** 2); } else { output[2 * cell] = scenario.freestream[0] ?? 0; output[2 * cell + 1] = scenario.freestream[1] ?? 0; } } return output; }
  private updateSolid(control: ControlState): void { const scenario = this.requireScenario(); const foil = this.foil; if (foil === null) throw new Error("foil is missing"); const {nx, ny, dx, dy} = dimensions(scenario.domain); const {x: bx, y: by} = bounds2d(scenario.domain); for (let y = 0; y < ny; y += 1) for (let x = 0; x < nx; x += 1) this.solid[y * nx + x] = foil.signedDistance(bx[0] + (x + 0.5) * dx, by[0] + (y + 0.5) * dy, control.angleDegrees) <= 0 ? 1 : 0; }

  private latticeFields(): {density: FloatArray; velocity: FloatArray} { const scenario = this.requireScenario(); const {nx, ny} = dimensions(scenario.domain); const count = nx * ny; const density = allocate(scenario.precision, count); const velocity = allocate(scenario.precision, 2 * count); for (let cell = 0; cell < count; cell += 1) { let rho = 0; let mx = 0; let my = 0; for (let q = 0; q < 9; q += 1) { const value = this.populations[q * count + cell] ?? 0; rho += value; mx += value * (CX[q] ?? 0); my += value * (CY[q] ?? 0); } density[cell] = rho; velocity[2 * cell] = mx / Math.max(rho, 1e-12); velocity[2 * cell + 1] = my / Math.max(rho, 1e-12); } return {density, velocity}; }

  private latticeStep(control: ControlState): void { const scenario = this.requireScenario(); const {nx, ny} = dimensions(scenario.domain); const count = nx * ny; this.updateSolid(control); const {density, velocity} = this.latticeFields(); const post = this.scratch; post.fill(0); for (let cell = 0; cell < count; cell += 1) { if (this.solid[cell] !== 0) continue; const rho = density[cell] ?? 1; const ux = velocity[2 * cell] ?? 0; const uy = velocity[2 * cell + 1] ?? 0; for (let q = 0; q < 9; q += 1) { const opposite = OPPOSITE[q] ?? 0; const f = this.populations[q * count + cell] ?? 0; const fo = this.populations[opposite * count + cell] ?? 0; const eq = this.equilibrium(q, rho, ux, uy); const eqo = this.equilibrium(opposite, rho, ux, uy); const symmetric = 0.5 * (f + fo); const antisymmetric = 0.5 * (f - fo); post[q * count + cell] = f - this.omegaPlus * (symmetric - 0.5 * (eq + eqo)) - this.omegaMinus * (antisymmetric - 0.5 * (eq - eqo)); } }
    const next = allocate(scenario.precision, this.populations.length); const inletUx = (scenario.freestream[0] ?? 0) * this.latticeSpeed / this.referenceSpeed; const inletUy = (scenario.freestream[1] ?? 0) * this.latticeSpeed / this.referenceSpeed; for (let cell = 0; cell < count; cell += 1) for (let q = 0; q < 9; q += 1) next[q * count + cell] = this.equilibrium(q, 1, inletUx, inletUy);
    const periodicX = scenario.domain.periodicAxes.includes("x"); const periodicY = scenario.domain.periodicAxes.includes("y");
    for (let y = 0; y < ny; y += 1) for (let x = 0; x < nx; x += 1) { const cell = y * nx + x; if (this.solid[cell] !== 0) continue; for (let q = 0; q < 9; q += 1) { let tx = x + (CX[q] ?? 0); let ty = y + (CY[q] ?? 0); const value = post[q * count + cell] ?? 0; if (periodicX) tx = (tx + nx) % nx; if (periodicY) ty = (ty + ny) % ny; if (tx < 0 || tx >= nx || ty < 0 || ty >= ny) continue; const target = ty * nx + tx; if (this.solid[target] !== 0) next[(OPPOSITE[q] ?? 0) * count + cell] = value; else next[q * count + target] = value; } }
    this.populations = next; this.scratch = post;
  }

  public advance(control: ControlState, targetDt: number): StepReport { if (!(targetDt > 0) || !Number.isFinite(targetDt)) throw new RangeError("target dt must be finite and positive"); const scenario = this.requireScenario(); const {dx} = dimensions(scenario.domain); const latticeDt = this.latticeSpeed * dx / this.referenceSpeed; const substeps = Math.max(1, Math.ceil(targetDt / latticeDt)); const saved = this.populations.slice(); try { for (let step = 0; step < substeps; step += 1) this.latticeStep(control); if (!this.populations.every(Number.isFinite)) throw new NumericalFailure("nonfinite_state", "LBM populations became non-finite"); } catch (error) { this.populations = saved; throw error; } this.time += targetDt; this.control = {...control, time: this.time}; const physical = this.physicalVelocity(); let maxSpeed = 0; for (let i = 0; i < physical.length; i += 2) maxSpeed = Math.max(maxSpeed, Math.hypot(physical[i] ?? 0, physical[i + 1] ?? 0)); return {requestedDt: targetDt, advancedDt: targetDt, substeps, maxSpeed, warnings: this.effectiveReynolds < this.reynolds ? ["effective Reynolds clamped to " + String(this.effectiveReynolds)] : []}; }
  private physicalVelocity(): FloatArray { const scenario = this.requireScenario(); const lattice = this.latticeFields().velocity; const output = allocate(scenario.precision, lattice.length); const scale = this.referenceSpeed / this.latticeSpeed; for (let i = 0; i < output.length; i += 1) output[i] = (lattice[i] ?? 0) * scale; return output; }
  public sampleVelocity(points: FloatArray): FloatArray { const scenario = this.requireScenario(); const velocity = this.physicalVelocity(); const output = allocate(scenario.precision, points.length); for (let i = 0; i < points.length; i += 2) { const value = sampleCell(velocity, scenario.domain, points[i] ?? 0, points[i + 1] ?? 0); output[i] = value[0]; output[i + 1] = value[1]; } return output; }
  public exportState(): CanonicalFlowState { const scenario = this.requireScenario(); return {schemaVersion: 1, dimension: 2, bounds: scenario.domain.bounds, resolution: scenario.domain.resolution, periodicAxes: scenario.domain.periodicAxes, time: this.time, precision: scenario.precision, angleDegrees: this.control.angleDegrees, angularVelocityDegrees: this.control.angularVelocityDegrees, sourceLanguage: "typescript", sourceSolver: this.info.id, velocity: this.physicalVelocity(), density: this.latticeFields().density}; }
  public importState(state: CanonicalFlowState, control: ControlState): ImportOutcome { const scenario = this.requireScenario(); const {nx, ny} = dimensions(scenario.domain); if (state.dimension !== 2 || state.resolution[0] !== nx || state.resolution[1] !== ny) return {status: "rejected", reason: "incompatible_domain", discardedState: [], warnings: []}; if (!state.velocity.every(Number.isFinite)) return {status: "rejected", reason: "nonfinite_state", discardedState: [], warnings: []}; const count = nx * ny; const density = state.density; for (let cell = 0; cell < count; cell += 1) for (let q = 0; q < 9; q += 1) this.populations[q * count + cell] = this.equilibrium(q, density?.[cell] ?? 1, (state.velocity[2 * cell] ?? 0) * this.latticeSpeed / this.referenceSpeed, (state.velocity[2 * cell + 1] ?? 0) * this.latticeSpeed / this.referenceSpeed); this.time = state.time; this.control = control; this.updateSolid(control); return {status: "accepted", reason: "none", discardedState: ["non-equilibrium populations"], warnings: []}; }
  public diagnostics(): Diagnostics { const scenario = this.requireScenario(); const foil = this.foil; if (foil === null) throw new Error("foil is missing"); const fields = this.latticeFields(); const velocity = this.physicalVelocity(); let densityDrift = 0; for (let cell = 0; cell < fields.density.length; cell += 1) densityDrift = Math.max(densityDrift, Math.abs((fields.density[cell] ?? 1) - 1)); return {values: {...fieldDiagnostics(velocity, scenario, foil, this.control.angleDegrees), density_drift_linf: densityDrift, effective_reynolds: this.effectiveReynolds}, warnings: []}; }
}
