import type {CanonicalFlowState, ControlState, Diagnostics, FlowSolver, FloatArray, ImportOutcome, Scenario, SolverInfo, StepReport} from "../core/contracts.js";
import {NacaFoil} from "../core/geometry.js";
import {allocate, bounds2d, dimensions, sampleCell} from "../core/grid.js";
import {Pcg32} from "../core/rng.js";
import {StableFluidsSolver} from "./stableFluids.js";

export class PicFlipSolver implements FlowSolver {
  public readonly info: SolverInfo = {id: "pic-flip", displayName: "Blended PIC/FLIP", dimensions: [2], supportsMovingBoundary: true, acceleration: "typed-arrays"};
  public get reynolds(): number { return this.grid.reynolds; }
  private readonly grid = new StableFluidsSolver(); private scenario: Scenario | null = null; private foil: NacaFoil | null = null;
  private x: FloatArray = new Float32Array(); private y: FloatArray = new Float32Array(); private vx: FloatArray = new Float32Array(); private vy: FloatArray = new Float32Array(); private generations = new Uint32Array(); private rng = new Pcg32(0, 71); private blend = 0.95; private advanceCount = 0;

  private requireScenario(): Scenario { if (this.scenario === null) throw new Error("solver is not initialized"); return this.scenario; }
  public initialize(scenario: Scenario, seed: number): void { if (scenario.domain.dimension !== 2) throw new RangeError("pic-flip supports only 2D"); this.scenario = scenario; this.foil = new NacaFoil(scenario.foil); this.blend = scenario.solverOptions.picFlipBlend ?? 0.95; this.rng = new Pcg32(seed, 71); this.advanceCount = 0; this.grid.initialize(scenario, seed); this.seedParticles(); }
  public setReynolds(reynolds: number): void { this.grid.setReynolds(reynolds); }

  private seedParticles(): void { const scenario = this.requireScenario(); const {nx, ny, dx, dy} = dimensions(scenario.domain); const {x: bx, y: by} = bounds2d(scenario.domain); const count = 4 * nx * ny; this.x = allocate(scenario.precision, count); this.y = allocate(scenario.precision, count); this.vx = allocate(scenario.precision, count); this.vy = allocate(scenario.precision, count); this.generations = new Uint32Array(count); let particle = 0; for (let cy = 0; cy < ny; cy += 1) for (let cx = 0; cx < nx; cx += 1) for (let local = 0; local < 4; local += 1) { this.x[particle] = bx[0] + (cx + 0.15 + 0.7 * this.rng.nextFloat32()) * dx; this.y[particle] = by[0] + (cy + 0.15 + 0.7 * this.rng.nextFloat32()) * dy; particle += 1; } const velocity = this.grid.sampleVelocity(this.interleavedPositions()); for (let index = 0; index < count; index += 1) { this.vx[index] = velocity[2 * index] ?? 0; this.vy[index] = velocity[2 * index + 1] ?? 0; } }
  private interleavedPositions(): FloatArray { const scenario = this.requireScenario(); const output = allocate(scenario.precision, 2 * this.x.length); for (let index = 0; index < this.x.length; index += 1) { output[2 * index] = this.x[index] ?? 0; output[2 * index + 1] = this.y[index] ?? 0; } return output; }
  private respawn(index: number): void { const scenario = this.requireScenario(); const foil = this.foil; if (foil === null) throw new Error("foil is missing"); const {x: bx, y: by} = bounds2d(scenario.domain); for (let attempt = 0; attempt < 16; attempt += 1) { const px = bx[0] + this.rng.nextFloat32() * (bx[1] - bx[0]); const py = by[0] + this.rng.nextFloat32() * (by[1] - by[0]); if (foil.signedDistance(px, py, 0) > 0) { this.x[index] = px; this.y[index] = py; this.vx[index] = scenario.freestream[0] ?? 0; this.vy[index] = scenario.freestream[1] ?? 0; this.generations[index] = (this.generations[index] ?? 0) + 1; return; } } }
  private quadraticWeight(distance: number): number { const value = Math.abs(distance); if (value < 0.5) return 0.75 - value * value; if (value < 1.5) return 0.5 * (1.5 - value) ** 2; return 0; }
  private scatterToGrid(fallback: CanonicalFlowState): FloatArray { const scenario = this.requireScenario(); const {nx, ny, dx, dy} = dimensions(scenario.domain); const {x: bx, y: by} = bounds2d(scenario.domain); const output = allocate(scenario.precision, 2 * nx * ny); const weights = allocate(scenario.precision, nx * ny); for (let particle = 0; particle < this.x.length; particle += 1) { const gx = ((this.x[particle] ?? 0) - bx[0]) / dx - 0.5; const gy = ((this.y[particle] ?? 0) - by[0]) / dy - 0.5; const baseX = Math.floor(gx); const baseY = Math.floor(gy); for (let oy = -1; oy <= 1; oy += 1) for (let ox = -1; ox <= 1; ox += 1) { const cx = baseX + ox; const cy = baseY + oy; if (cx < 0 || cx >= nx || cy < 0 || cy >= ny) continue; const weight = this.quadraticWeight(gx - cx) * this.quadraticWeight(gy - cy); const cell = cy * nx + cx; output[2 * cell] = (output[2 * cell] ?? 0) + weight * (this.vx[particle] ?? 0); output[2 * cell + 1] = (output[2 * cell + 1] ?? 0) + weight * (this.vy[particle] ?? 0); weights[cell] = (weights[cell] ?? 0) + weight; } }
    for (let cell = 0; cell < nx * ny; cell += 1) { const weight = weights[cell] ?? 0; if (weight > 1e-8) { output[2 * cell] = (output[2 * cell] ?? 0) / weight; output[2 * cell + 1] = (output[2 * cell + 1] ?? 0) / weight; } else { output[2 * cell] = fallback.velocity[2 * cell] ?? 0; output[2 * cell + 1] = fallback.velocity[2 * cell + 1] ?? 0; } } return output; }

  public advance(control: ControlState, targetDt: number): StepReport { const scenario = this.requireScenario(); const oldGrid = this.grid.exportState(); const oldSamples = this.grid.sampleVelocity(this.interleavedPositions()); const report = this.grid.advance(control, targetDt); const newGrid = this.grid.exportState(); const positions = this.interleavedPositions(); const newSamples = this.grid.sampleVelocity(positions); const {x: bx, y: by} = bounds2d(scenario.domain); const foil = this.foil; if (foil === null) throw new Error("foil is missing"); for (let index = 0; index < this.x.length; index += 1) { const flipX = (this.vx[index] ?? 0) + (newSamples[2 * index] ?? 0) - (oldSamples[2 * index] ?? 0); const flipY = (this.vy[index] ?? 0) + (newSamples[2 * index + 1] ?? 0) - (oldSamples[2 * index + 1] ?? 0); this.vx[index] = this.blend * flipX + (1 - this.blend) * (newSamples[2 * index] ?? 0); this.vy[index] = this.blend * flipY + (1 - this.blend) * (newSamples[2 * index + 1] ?? 0); const midpointX = (this.x[index] ?? 0) + 0.5 * targetDt * (newSamples[2 * index] ?? 0); const midpointY = (this.y[index] ?? 0) + 0.5 * targetDt * (newSamples[2 * index + 1] ?? 0); const midpoint = sampleCell(newGrid.velocity, scenario.domain, midpointX, midpointY); this.x[index] = (this.x[index] ?? 0) + targetDt * midpoint[0]; this.y[index] = (this.y[index] ?? 0) + targetDt * midpoint[1]; const px = this.x[index] ?? 0; const py = this.y[index] ?? 0; if (px < bx[0] || px > bx[1] || py < by[0] || py > by[1] || foil.signedDistance(px, py, control.angleDegrees) <= 0) this.respawn(index); }
    this.advanceCount += 1; const populationInterval = scenario.solverOptions.picPopulationInterval ?? 8; if (this.advanceCount % populationInterval === 0) for (let index = 0; index < this.x.length; index += 1) if (!Number.isFinite(this.x[index]) || !Number.isFinite(this.y[index])) this.respawn(index); const transferred = this.scatterToGrid(newGrid); const state = {...newGrid, sourceSolver: this.info.id, velocity: transferred}; const outcome = this.grid.importState(state, control); if (outcome.status === "rejected") { this.grid.importState(oldGrid, control); throw new Error(`PIC/FLIP grid transfer rejected: ${outcome.reason}`); } return report; }
  public sampleVelocity(points: FloatArray): FloatArray { return this.grid.sampleVelocity(points); }
  public exportState(): CanonicalFlowState { return {...this.grid.exportState(), sourceSolver: this.info.id}; }
  public importState(state: CanonicalFlowState, control: ControlState): ImportOutcome { const outcome = this.grid.importState(state, control); if (outcome.status === "rejected") return outcome; this.seedParticles(); return {status: "accepted", reason: "none", discardedState: [...outcome.discardedState, "solver particles", "FLIP deltas"], warnings: []}; }
  public diagnostics(): Diagnostics { const diagnostics = this.grid.diagnostics(); return {values: {...diagnostics.values, particle_count: this.x.length, pic_flip_blend: this.blend}, warnings: diagnostics.warnings}; }
}
