import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {describe, expect, it} from "vitest";
import {controlAt, parseScenario} from "../../src/core/scenario.js";
import {NacaFoil} from "../../src/core/geometry.js";
import {bounds2d, dimensions} from "../../src/core/grid.js";
import {convectiveOutletPopulation, LbmSolver} from "../../src/solvers/lbm.js";

describe("D2Q9 TRT LBM contract", () => {
  it("advects outlet populations from their previous boundary state", () => {
    expect(convectiveOutletPopulation(0.25, 1, 0.08)).toBeCloseTo(0.31, 14);
    expect(convectiveOutletPopulation(1, 0.25, 0.08)).toBeCloseTo(0.94, 14);
  });
  it("advances finite populations and canonical fields", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/validation/uniform.json"), "utf8")) as unknown; const scenario = parseScenario(raw, schema); const solver = new LbmSolver(); solver.initialize(scenario, 0); expect(solver.advance(controlAt(scenario, 0.01), 0.01).advancedDt).toBeCloseTo(0.01); expect(solver.exportState().velocity.every(Number.isFinite)).toBe(true); expect(solver.exportState().density?.every(Number.isFinite)).toBe(true); });
  it("rejects invalid density and reconstructs finite high-speed fields", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/validation/uniform.json"), "utf8")) as unknown; const scenario = parseScenario(raw, schema); const solver = new LbmSolver(); solver.initialize(scenario, 0); const control = controlAt(scenario, 0); const state = solver.exportState(); if (state.density === null) throw new Error("LBM density missing"); const invalidDensity = state.density.slice(); invalidDensity[0] = -1; expect(solver.importState({...state, density: invalidDensity}, control).reason).toBe("invalid_density"); const highSpeed = state.velocity.slice(); highSpeed[0] = 100; const outcome = solver.importState({...state, velocity: highSpeed}, control); expect(outcome.status).toBe("accepted"); expect(solver.exportState().velocity.every(Number.isFinite)).toBe(true); });
  it("uses exact requested intervals at non-nominal step sizes", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/validation/uniform.json"), "utf8")) as unknown; const scenario = parseScenario(raw, schema); const solver = new LbmSolver(); solver.initialize(scenario, 0); for (const targetDt of [0.007, 0.013, 0.02]) { const before = solver.exportState().time; const report = solver.advance(controlAt(scenario, before + targetDt), targetDt); expect(report.advancedDt).toBe(targetDt); expect(solver.exportState().time).toBeCloseTo(before + targetDt, 12); expect(solver.exportState().velocity.every(Number.isFinite)).toBe(true); } });
  it("ignores finite out-of-envelope density at authoritative solid centers", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/airfoil/default.json"), "utf8")) as unknown; const scenario = parseScenario(raw, schema); const source = new LbmSolver(); source.initialize(scenario, 0); const state = source.exportState(); if (state.density === null) throw new Error("LBM density missing"); const density = state.density.slice(); const foil = new NacaFoil(scenario.foil); const {nx, ny, dx, dy} = dimensions(scenario.domain); const {x: bx, y: by} = bounds2d(scenario.domain); for (let y = 0; y < ny; y += 1) for (let x = 0; x < nx; x += 1) if (foil.signedDistance(bx[0] + (x + 0.5) * dx, by[0] + (y + 0.5) * dy, state.angleDegrees) <= 0) density[y * nx + x] = 100; const destination = new LbmSolver(); destination.initialize(scenario, 0); expect(destination.importState({...state, density}, {time: state.time, angleDegrees: state.angleDegrees, angularVelocityDegrees: state.angularVelocityDegrees}).status).toBe("accepted"); });
});
