import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {describe, expect, it} from "vitest";
import {controlAt, parseScenario} from "../../src/core/scenario.js";
import {PicFlipSolver} from "../../src/solvers/picFlip.js";

describe("blended PIC/FLIP contract", () => {
  it("advances deterministic solver particles and finite grid state", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/validation/uniform.json"), "utf8")) as unknown; const scenario = parseScenario(raw, schema); const solver = new PicFlipSolver(); solver.initialize(scenario, scenario.seed); expect(solver.diagnostics().values["particle_count"]).toBe(4 * (scenario.domain.resolution[0] ?? 0) * (scenario.domain.resolution[1] ?? 0)); expect(solver.advance(controlAt(scenario, 0.01), 0.01).advancedDt).toBeCloseTo(0.01); expect(solver.exportState().velocity.every(Number.isFinite)).toBe(true); });
  it("uses the configured particle CFL and rejects invalid values", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/validation/uniform.json"), "utf8")) as unknown; const loaded = parseScenario(raw, schema); const scenario = {...loaded, domain: {...loaded.domain, resolution: [24, 12]}, solverOptions: {...loaded.solverOptions, picCfl: 0.25}}; const solver = new PicFlipSolver(); solver.initialize(scenario, 0); expect(solver.advance(controlAt(scenario, 0.1), 0.1).substeps).toBeGreaterThan(1); const invalid = new PicFlipSolver(); expect(() => invalid.initialize({...scenario, solverOptions: {...scenario.solverOptions, picCfl: 1.1}}, 0)).toThrow(/pic_cfl/); });
  it("reports deterministic PIC-dominant settling after canonical import", async () => { const schema = JSON.parse(await readFile(resolve("../../spec/scenario.schema.json"), "utf8")) as object; const raw = JSON.parse(await readFile(resolve("../../scenarios/validation/uniform.json"), "utf8")) as unknown; const scenario = parseScenario(raw, schema); const source = new PicFlipSolver(); source.initialize(scenario, 0); const destination = new PicFlipSolver(); destination.initialize(scenario, 0); const outcome = destination.importState(source.exportState(), controlAt(scenario, 0)); expect(outcome.status).toBe("accepted"); expect(outcome.warnings).toContain("solver particles reseeded; first step is PIC-dominant"); expect(destination.advance(controlAt(scenario, 0.01), 0.01).advancedDt).toBe(0.01); });
});
